### ISSUE TITLE
Proposol: Implement zipmap

### ISSUE THREAD

**Issue by zsoerenm** [tshort/ReactiveBasics.jl#18]
I often find myself writing things like this:

```julia
as = Signal(1)
bs = map(a -> a * 0.1, as)
map(values -> ((a, b) = values; a + b), zip(as, bs))
```
However doing `(a, b) = values; #...` seems very kludgy.

So my proposel is to define a zipmap like this:

```julia
function zipmap(f, u::Signal, us::Signal...)
    zipped_signal = zip(u, us...)
    signal = Signal(f(zipped_signal.value...))
    subscribe!(x -> push!(signal, f(x...)), zipped_signal)
    signal
end
```
Now the same above is as easy as
```julia
as = Signal(1)
bs = map(a -> a * 0.1, as)
zipmap((a, b) -> a + b, as, bs)
```
Another approach would by to let Base.map expand tuples right away, so that 
```julia
map((a, b) -> a + b, zip(as, bs))
```
works

**Comment by tshort** [comment]
I'm good with adding a `zipmap` for that use case.

**Comment by tshort** [comment]
Just to be clear, can you fill me in on why you want that over just:

```julia
ds = map((a,b) -> a + b, as, bs)
```

Does the zip in there get rid of a duplicate calculation? If that's it, maybe this should be baked into `map`.

**Comment by zsoerenm** [comment]
Yes, zip gets rid of duplicate calculation in cases when two or more signals are meant to update at the same time.
This is not always desired, though. It is completely fine to map two different signals that update on different time stamps. In this case the mapped signal should update on either input signal. So turning `map` into `zipmap` is probably not what we want.

 `Base.map` could, however, be modified in a way, that it always expands Tuples like this:
```julia
function Base.map(f, u::Signal)
    signal = Signal(f(u.value...)) # instead of Signal(f(u.value))
    subscribe!(x -> push!(signal, f(x...)), u) # instead of push!(signal, f(x))
    signal
end
```
In this case one could write:
```julia
map((a, b) -> a + b, zip(as, bs))
```

But this might not be adequate if the Signal is meant to contain Tuples

**Comment by tshort** [comment]
Thanks for the clear explanation, @zsoerenm. Based on that, having a separate `zipmap` function sounds best.

**Comment by zsoerenm** [comment]
That is impemented in latest master. So I'm closing this
